### ISSUE TITLE
Equals() and HashCode() methods

### ISSUE THREAD

**Issue by katHermanova** [xpalenik/PA165-Library#77]
- "Equals problems" from MS1 feedback
- "Missing equals and hashCode in some of DTO objects" from MS2 feedback

**Comment by xpalenik** [comment]
This seems to be done. Can you close it?

**Comment by katHermanova** [comment]
nope...still have to do it for DTO objects, sorry

**Comment by xpalenik** [comment]
No problem, just checking :+1: Take your time.
