### ISSUE TITLE
Wiring of the application

### ISSUE THREAD

**Issue by katHermanova** [xpalenik/PA165-Library#79]
- "The wiring of the application is unfortunate - you should not manually make
everything bean in cz.muni.fi.pa165.library.LibraryApplication especially if
 you are using SpringBoot, let the framework do the work. You are also using
field injection in some parts of the app
 e.g. - in some of the facades, also you are also mixing apples and oranges
with autowiring fields and actually using constructors" from MS2 feedback

**Comment by xpalenik** [comment]
I think it should be ok now, but I will ask Pačes to confirm if he cares to have a look at the whole project.

**Comment by katHermanova** [comment]
Sounds good, thanks :)
